class AppStrings {
  static const Map<String, Map<String, String>> _strings = {
    'ru': {
      // Common
      'appName': 'Курьер PRO Еда',
      'assistant': 'Помощник',
      'home': 'Главная',
      'income': 'Доход',
      'myPath': 'Мой путь',
      'deleteAccount': 'Удалить профиль',
      'deleteConfirm': 'Вы уверены, что хотите удалить профиль? Все сохраненные данные будут стёрты.',
      'cancel': 'Отмена',
      'delete': 'Удалить',
      'save': 'Сохранить',
      'profile': 'Личный кабинет',
      'name': 'Ваше имя',
      'phone': 'Номер телефона',
      'workCountry': 'Страна работы',
      'format': 'Формат доставки',
      'language': 'Язык приложения',
      'russia': 'Россия',
      'kazakhstan': 'Казахстан',
      'uzbekistan': 'Узбекистан',
      'kyrgyzstan': 'Кыргызстан',
      'belarus': 'Беларусь',
      'next': 'Далее →',
      'start': 'Начать →',
      
      // Language Selection
      'selectLanguage': 'Выберите язык',
      'selectLanguageSub': 'Вы сможете изменить язык в любой момент в профиле',
      
      // Onboarding 3-step
      'onb1Title': 'Высокий доход\nи выплаты каждый день',
      'onb1Subtitle': 'Ежедневные выплаты на карту любого банка. Гибкий график и бонусы за заказы.',
      'onb2Title': 'Твой транспорт —\nтвой график',
      'onb2Subtitle': 'Доставляйте пешком, на велосипеде или автомобиле. Слоты от 2 часов возле дома.',
      'onb3Title': 'Персональный\nпомощник',
      'onb3Subtitle': 'Пошагово поможем оформить документы онлайн и получить необходимое для работы за 1 день.',

      // Registration Cabinet
      'regCabinetTitle': 'Личный кабинет',
      'regCabinetSubtitle': 'Введите данные для связи с помощником и старта работы',
      'nameHint': 'Как к вам обращаться?',
      'continueBtn': 'Продолжить',
      'privacyNotice': 'Нажимая «Продолжить», вы принимаете условия использования',

      // Home Hub Cards
      'greeting': 'Привет',
      'chooseFormat': 'Выберите удобный формат доставки',
      'autoCourier': 'Автокурьер',
      'autoCourierIncome': 'от 3 500 ₽ / день',
      'autoCourierDesc': 'Радиус: весь город',
      'walkCourier': 'Пеший курьер',
      'walkCourierIncome': 'от 2 500 ₽ / день',
      'walkCourierDesc': 'Радиус: свой район',
      'motoCourier': 'Мотокурьер',
      'motoCourierIncome': 'от 3 000 ₽ / день',
      'motoCourierDesc': 'Без пробок и задержек',
      'bikeCourier': 'Велокурьер',
      'bikeCourierIncome': 'от 2 800 ₽ / день',
      'bikeCourierDesc': 'Быстрее пешего в 2 раза',
      'needHelpSnippet': 'Персональный помощник',
      'needHelpSubtitle': 'Задайте вопрос по документам или условиям >',

      // Assistant
            'assistantGreeting': 'Привет! 👋 Я твой личный куратор.\n\nПомогу быстро оформиться курьером в службу доставки, получить всё необходимое для работы и выйти на первые заказы уже завтра.\n\nНажми кнопку «Заполнить Анкету» ниже, чтобы заполнить анкету партнёра за пару минут, или задай мне любой вопрос в чате!',
            'chipFastReg': '🚀 Сразу к анкете',
      'chipWalk': 'Пешком 🚶',
      'chipBike': 'На велосипеде 🚲',
      'chipCar': 'На авто 🚗',
      'chipMoto': 'На мото 🏍️',
      'chipError': '🛠️ Ошибка в приложении / Мой налог',
      'chipDocs': '📄 Документы для граждан СНГ',
      'chipAge': '🎂 Со скольки лет?',
      'chipFines': '⚡ Штрафы и термокороб',
      'inputHint': 'Задайте вопрос помощнику...',
      'regCardTitle': 'Официальная анкета партнёра',
      'regCardPerk1': 'Выплаты каждый день на карту',
            'regCardPerk2': 'Получить необходимое для работы',
            'regCardPerk3': 'Свободный график от 1 часа',
            'regCardBtn': 'Заполнить Анкету',

            // Sticky CTA Banner
            'cta_fill_anketa': 'Заполнить Анкету',
            'cta_fill_anketa_sub': 'Официальная анкета партнёра — 2 минуты',
            'cta_continue_reg': 'Продолжить регистрацию',
            'cta_continue_reg_sub': 'Куратор поможет пройти оставшиеся шаги',
            'cta_get_bag': 'Забрать сумку',
            'cta_get_bag_sub': 'Получи термосумку и выходи на линию',
            'cta_open_income': 'Открыть Доход',
            'cta_open_income_sub': 'Посчитай заработок за смену',

            // Calculator
      'calcTitle': 'Расчёт дохода',
      'daysPerWeek': 'Дней в неделю',
      'hoursPerDay': 'Часов в день',
      'approxIncome': 'Потенциальный доход',
      'month': 'мес',
      'goals': 'Ваши цели',
      'goalIphone': '📱 Новый iPhone 16',
      'goalScooter': '🛵 Электросамокат',
      'goalVacation': '✈️ Отпуск на море',
      'shifts': 'смен',
      'startEarning': 'Начать зарабатывать на цель →',

      // Roadmap
      'roadmapTitle': 'Мой путь до 5 заказов',
      'roadmapSubtitle': 'Выполните 5 доставок, чтобы закрепить статус партнёра и открыть максимальные бонусы!',
      'step1': 'Заполнить анкету партнёра',
      'step1Desc': 'Онлайн-анкета занимает 3 минуты',
      'step2': 'Связка с «Мой налог»',
      'step2Desc': 'Партнёры → Сервис Еда → Разрешить',
      'step3': 'Получить необходимое для работы',
      'step3Desc': 'В пункте выдачи (ПВЗ) или Курьерском центре',
      'step4': 'Первый выполненный заказ',
      'step4Desc': 'Поддержка на первом слоте от помощника',
      'step5': '5 заказов = Бонус новичка!',
      'step5Desc': 'Разблокировка максимальных тарифов и выплат',
      'openGuide': '📖 Пошаговая шпаргалка в картинках',
      'vpnWarning': '⚠️ Важно: при ошибках в приложении выключите VPN!',

            // Proactive Questions (Sprint 2)
            'proactive_pre_registration': 'Какой район тебе ближе для старта?',
            'proactive_registration_sent': 'Нужна инструкция по «Мой налог» прямо сейчас?',
            'proactive_post_registration': 'Какой ЦО тебе удобнее?',
            'proactive_active_courier': 'Как заказы вчера? Есть вопросы по тарифам?',
            'proactive_churned_risk': 'Что мешает выйти на линию? Могу помочь с документами/зоной.',

                        // Self-Report Buttons (Sprint 3)
                        'btnBagReceived': 'Я получил сумку',
                        'btnFirstOrderDone': 'Сделал первый заказ',
                        'btnMoyNalogLinked': 'Мой налог привязан',
                        'selfReportBagReceived': 'Отлично! Сумка получена — теперь можно выходить на заказы. Нужна помощь с первым слотом?',
                        'selfReportFirstOrderDone': '🎉 Первый заказ выполнен! Молодец. Продолжай в том же духе — к бонусам новичка близко.',
                        'selfReportMoyNalogLinked': '✅ «Мой налог» привязан. Теперь выплаты будут приходить автоматически.',
                      },

                      'uz': {
      // Common
      'appName': 'Kuryer PRO Eda',
      'assistant': 'Yordamchi',
      'home': 'Bosh sahifa',
      'income': 'Daromad',
      'myPath': 'Mening yo‘lim',
      'deleteAccount': 'Profilni o‘chirish',
      'deleteConfirm': 'Haqiqatan ham profilingizni o‘chirmoqchimisiz? Barcha ma’lumotlar o‘chiriladi.',
      'cancel': 'Bekor qilish',
      'delete': 'O‘chirish',
      'save': 'Saqlash',
      'profile': 'Shaxsiy kabinet',
      'name': 'Ismingiz',
      'phone': 'Telefon raqam',
      'workCountry': 'Ishlash davlati',
      'format': 'Yetkazib berish turi',
      'language': 'Ilova tili',
      'russia': 'Rossiya',
      'kazakhstan': 'Qozog‘iston',
      'uzbekistan': 'O‘zbekiston',
      'kyrgyzstan': 'Qirg‘iziston',
      'belarus': 'Belarus',
      'next': 'Keyingisi →',
      'start': 'Boshlash →',
      
      // Language Selection
      'selectLanguage': 'Tilni tanlang',
      'selectLanguageSub': 'Ilova tilini profilingizda istalgan vaqtda o‘zgartirishingiz mumkin',

      // Onboarding 3-step
      'onb1Title': 'Yetkazib berish\norqali pul ishlang',
      'onb1Subtitle': 'oyiga 85 000 ₽ dan. Qulay grafik. O‘zingizga qulay vaqtda ishlang.',
      'onb2Title': 'Sizni bosqichma-bosqich\nyo‘naltiramiz',
      'onb2Subtitle': 'Hujjatlarni to‘plash va birinchi buyurtmani bajarishda yordam beramiz.',
      'onb3Title': 'Shaxsiy yordamchi\n24/7 yoningizda',
      'onb3Subtitle': 'Qanday hujjatlar kerak? Xatolik bo‘lsa nima qilish kerak? — yordamchidan so‘rang.',

      // Registration Cabinet
      'regCabinetTitle': 'Shaxsiy kabinet',
      'regCabinetSubtitle': 'Yordamchi bilan bog‘lanish va ish boshlash uchun ma’lumot kiriting',
      'nameHint': 'Ismingiz nima?',
      'continueBtn': 'Davom etish',
      'privacyNotice': '«Davom etish»ni bosish orqali foydalanish shartlariga rozilik bildirasiz',

      // Home Hub Cards
      'greeting': 'Salom',
      'chooseFormat': 'Qulay yetkazib berish turini tanlang',
      'autoCourier': 'Avto kuryer',
      'autoCourierIncome': 'kuniga 3 500 ₽ dan',
      'autoCourierDesc': 'Radius: butun shahar',
      'walkCourier': 'Piyoda kuryer',
      'walkCourierIncome': 'kuniga 2 500 ₽ dan',
      'walkCourierDesc': 'Radius: o‘z hududingiz',
      'motoCourier': 'Moto kuryer',
      'motoCourierIncome': 'kuniga 3 000 ₽ dan',
      'motoCourierDesc': 'Tirbandliklarsiz tez',
      'bikeCourier': 'Velo kuryer',
      'bikeCourierIncome': 'kuniga 2 800 ₽ dan',
      'bikeCourierDesc': 'Piyodadan 2 barobar tez',
      'needHelpSnippet': 'Shaxsiy yordamchi',
      'needHelpSubtitle': 'Hujjatlar yoki shartlar bo‘yicha savol bering >',

      // Assistant
      'assistantGreeting': 'Salom! 👋 Men sizning shaxsiy kuratoringizman.\n\nYetkazib berish xizmatiga tezda ro‘yxatdan o‘tish, ish uchun zarur narsalarni olish va ertagayoq buyurtmalarga chiqishda yordam beraman.\n\nHamkor anketasini to‘ldirish uchun quyidagi «Ro‘yxatdan o‘tish» tugmasini bosing yoki menga savol bering!',
      'chipFastReg': '🚀 To‘g‘ridan-to‘g‘ri anketaga',
      'chipWalk': 'Piyoda 🚶',
      'chipBike': 'Velosipedda 🚲',
      'chipCar': 'Avtomobilda 🚗',
      'chipMoto': 'Mototsiklda 🏍️',
      'chipError': '🛠️ Ilovada xatolik / Mening solig‘im',
      'chipDocs': '📄 MDH fuqarolari uchun hujjatlar',
      'chipAge': '🎂 Necha yoshdan?',
      'chipFines': '⚡ Jarimalar va termasumka',
      'inputHint': 'Yordamchiga savol bering...',
      'regCardTitle': 'Hamkorning rasmiy anketasi',
            'regCardPerk1': 'Har kuni kartaga to‘lovlar',
            'regCardPerk2': 'Ish uchun barcha zarur narsalar',
            'regCardPerk3': '1 soatdan boshlab erkin jadval',
            'regCardBtn': 'Anketani to‘ldirish',

                  // Sticky CTA Banner
                  'cta_fill_anketa': 'Anketani to‘ldirish',
                  'cta_fill_anketa_sub': 'Rasmiy hamkor anketasi — 2 daqiqa',
                  'cta_continue_reg': 'Ro‘yxatdan o‘tishni davom ettirish',
                  'cta_continue_reg_sub': 'Kurator qolgan qadamlarni o‘tkazishda yordam beradi',
                  'cta_get_bag': 'Sumkani olish',
                  'cta_get_bag_sub': 'Termosumkani oling va ishga chiqing',
                  'cta_open_income': 'Daromadni ochish',
                  'cta_open_income_sub': 'Smenadagi ishlash haqi hisoblash',

                  // Calculator
      'calcTitle': 'Daromad hisobi',
      'daysPerWeek': 'Haftada kunlar',
      'hoursPerDay': 'Kuniga soatlar',
      'approxIncome': 'Kutilayotgan daromad',
      'month': 'oy',
      'goals': 'Sizning maqsadlaringiz',
      'goalIphone': '📱 Yangi iPhone 16',
      'goalScooter': '🛵 Elektrosamokat',
      'goalVacation': '✈️ Dengizga sayohat',
      'shifts': 'smena',
      'startEarning': 'Maqsadga erishish uchun boshlash →',

      // Roadmap
      'roadmapTitle': '5 ta buyurtmagacha yo‘lim',
      'roadmapSubtitle': 'Maksimal bonuslarni ochish uchun 5 ta buyurtmani bajaring!',
      'step1': 'Hamkor anketasini to‘ldirish',
      'step1Desc': 'Onlayn anketa 3 daqiqa oladi',
      'step2': '«Mening solig‘im»ga ulash',
      'step2Desc': 'Hamkorlar → Eda xizmati → Ruxsat berish',
      'step3': 'Ish uchun zarur narsalarni olish',
      'step3Desc': 'Berish punkti yoki kuryerlik markazida',
      'step4': 'Birinchi bajarilgan buyurtma',
      'step4Desc': 'Birinchi smenada yordamchidan ko‘mak',
      'step5': '5 ta buyurtma = Yangi boshlovchi bonusi!',
      'step5Desc': 'Maksimal tariflar va to‘lovlar ochiladi',
      'openGuide': '📖 Rasmli qo‘llanma',
      'vpnWarning': '⚠️ Muhim: ilovada xatolik bo‘lsa, VPN-ni o‘chiring!',
    },

    'kg': {
      // Common
      'appName': 'Курьер PRO Еда',
      'assistant': 'Жардамчы',
      'home': 'Башкы бет',
      'income': 'Киреше',
      'myPath': 'Менин жолум',
      'deleteAccount': 'Профилди өчүрүү',
      'deleteConfirm': 'Чын эле профилди өчүргүңүз келеби? Бардык маалыматтар өчүрүлөт.',
      'cancel': 'Жокко чыгаруу',
      'delete': 'Өчүрүү',
      'save': 'Сактоо',
      'profile': 'Жеке кабинет',
      'name': 'Сиздин атыңыз',
      'phone': 'Телефон номери',
      'workCountry': 'Иштөө өлкөсү',
      'format': 'Жеткирүү түрү',
      'language': 'Тилди тандоо',
      'russia': 'Россия',
      'kazakhstan': 'Казакстан',
      'uzbekistan': 'Өзбекстан',
      'kyrgyzstan': 'Кыргызстан',
      'belarus': 'Беларусь',
      'next': 'Андан ары →',
      'start': 'Баштоо →',

      // Language Selection
      'selectLanguage': 'Тилди тандаңыз',
      'selectLanguageSub': 'Тилди профилден каалаган убакта өзгөртө аласыз',

      // Onboarding 3-step
      'onb1Title': 'Тамак жеткирип\nакча тап',
      'onb1Subtitle': 'айына 85 000 ₽ дан. Ыңгайлуу график. Өзүңүзгө жаккан убакта чыгыңыз.',
      'onb2Title': 'Башынан аягына чейин\nколдойбуз',
      'onb2Subtitle': 'Документтерди чогултууга жана биринчи тапшырыкка чыгууга жардам беребиз.',
      'onb3Title': 'Жеке жардамчы\n24/7 байланышта',
      'onb3Subtitle': 'Кайсы документтер керек? Ката чыкса эмне кылуу керек? — жардамчыдан сураңыз.',

      // Registration Cabinet
      'regCabinetTitle': 'Жеке кабинет',
      'regCabinetSubtitle': 'Жардамчы менен байланышуу жана ишти баштоо үчүн маалымат жазыңыз',
      'nameHint': 'Атыңыз ким?',
      'continueBtn': 'Улантуу',
      'privacyNotice': '«Улантуу» баскычын басуу менен колдонуу шарттарына макул болосуз',

      // Home Hub Cards
      'greeting': 'Салам',
      'chooseFormat': 'Ыңгайлуу жеткирүү түрүн тандаңыз',
      'autoCourier': 'Автокурьер',
      'autoCourierIncome': 'күнүнө 3 500 ₽ дан',
      'autoCourierDesc': 'Радиус: бүтүндөй шаар',
      'walkCourier': 'Жөө курьер',
      'walkCourierIncome': 'күнүнө 2 500 ₽ дан',
      'walkCourierDesc': 'Радиус: өз районуңуз',
      'motoCourier': 'Мотокурьер',
      'motoCourierIncome': 'күнүнө 3 000 ₽ дан',
      'motoCourierDesc': 'Тыгындарсыз тез',
      'bikeCourier': 'Велокурьер',
      'bikeCourierIncome': 'күнүнө 2 800 ₽ дан',
      'bikeCourierDesc': 'Жөө баскандан 2 эсе ылдам',
      'needHelpSnippet': 'Жеке жардамчы',
      'needHelpSubtitle': 'Документтер же шарттар боюнча суроо бериңиз >',

      // Assistant
      'assistantGreeting': 'Салам! 👋 Мен сиздин жеке кураторуңузмун.\n\nЖеткирүү кызматына тез катталууга, иш үчүн керектүү бардык нерселерди алууга жана эртең эле буйрутмаларга чыгууга жардам берем.\n\nӨнөктөш анкетасын толтуруу үчүн төмөнкү «Катталуу» баскычын басыңыз же мага суроо бериңиз!',
      'chipFastReg': '🚀 Дароо анкетага',
      'chipWalk': 'Жөө 🚶',
      'chipBike': 'Велосипед менен 🚲',
      'chipCar': 'Авто менен 🚗',
      'chipMoto': 'Мото менен 🏍️',
      'chipError': '🛠️ Тиркемедеги ката / Менин салыгым',
      'chipDocs': '📄 КМШ жарандары үчүн документтер',
      'chipAge': '🎂 Канча жаштан?',
      'chipFines': '⚡ Айыптар жана термосумка',
      'inputHint': 'Жардамчыга суроо бериңиз...',
      'regCardTitle': 'Өнөктөштүн расмий анкетасы',
            'regCardPerk1': 'Күндө картага төлөмдөр',
            'regCardPerk2': 'Иш үчүн керектүү бардык нерселер',
            'regCardPerk3': '1 сааттан баштап бош график',
            'regCardBtn': 'Анкетасын толтуруу',

                  // Sticky CTA Banner
                  'cta_fill_anketa': 'Анкетасын толтуруу',
                  'cta_fill_anketa_sub': 'Расмий шеріктеш анкетасы — 2 мүнөт',
                  'cta_continue_reg': 'Каттоочу жөнөтүү',
                  'cta_continue_reg_sub': 'Куратор калган кадамдарды өткөздө жардам берет',
                  'cta_get_bag': 'Сумканы алуу',
                  'cta_get_bag_sub': 'Термосумканы алганда, иштөөгө чыгыңыз',
                  'cta_open_income': 'Кирешені ачуу',
                  'cta_open_income_sub': 'Сменадагы жумуш акысын эсептөө',

                  // Calculator
      'calcTitle': 'Киреше эсептөө',
      'daysPerWeek': 'Аптадагы күндөр',
      'hoursPerDay': 'Күндөгү сааттар',
      'approxIncome': 'Болжолдуу киреше',
      'month': 'ай',
      'goals': 'Сиздин максаттар',
      'goalIphone': '📱 Жаңы iPhone 16',
      'goalScooter': '🛵 Электросамокат',
      'goalVacation': '✈️ Деңизге эс алуу',
      'shifts': 'смена',
      'startEarning': 'Максатка жетүү үчүн баштоо →',

      // Roadmap
      'roadmapTitle': '5 тапшырыкка чейин жолум',
      'roadmapSubtitle': 'Максималдуу бонустарды алуу үчүн 5 жеткирүүнү аткарыңыз!',
      'step1': 'Өнөктөш анкетасын толтуруу',
      'step1Desc': 'Онлайн анкета 3 мүнөт алат',
      'step2': '«Менин салыгым» тиркемесине кошуу',
      'step2Desc': 'Өнөктөштөр → Еда кызматы → Уруксат берүү',
      'step3': 'Иш үчүн керектүү нерселерди алуу',
      'step3Desc': 'Берүү түйүнүндө же курьердик борбордо',
      'step4': 'Биринчи аткарылган тапшырык',
      'step4Desc': 'Биринчи сменде жардамчыдан колдоо',
      'step5': '5 тапшырык = Жаңы баштагандын бонусу!',
      'step5Desc': 'Максималдуу тарифтер жана төлөмдөр ачылат',
      'openGuide': '📖 Сүрөттүү колдонмо',
      'vpnWarning': '⚠️ Маанилүү: ката чыкса, VPN-ди өчүрүңүз!',
    },

    'kz': {
      // Common
      'appName': 'Курьер PRO Еда',
      'assistant': 'Көмекші',
      'home': 'Басты бет',
      'income': 'Кіріс',
      'myPath': 'Менің жолым',
      'deleteAccount': 'Профильді жою',
      'deleteConfirm': 'Профильді жойғыңыз келетініне сенімдісіз бе? Барлық сақталған деректер өшіріледі.',
      'cancel': 'Бас тарту',
      'delete': 'Жою',
      'save': 'Сақтау',
      'profile': 'Жеке кабинет',
      'name': 'Сіздің атыңыз',
      'phone': 'Телефон нөмірі',
      'workCountry': 'Жұмыс елі',
      'format': 'Жеткізу түрі',
      'language': 'Қолданба тілі',
      'russia': 'Ресей',
      'kazakhstan': 'Қазақстан',
      'uzbekistan': 'Өзбекстан',
      'kyrgyzstan': 'Қырғызстан',
      'belarus': 'Беларусь',
      'next': 'Келесі →',
      'start': 'Бастау →',

      // Language Selection
      'selectLanguage': 'Тілді таңдаңыз',
      'selectLanguageSub': 'Тілді кез келген уақытта профильден өзгерте аласыз',

      // Onboarding 3-step
      'onb1Title': 'Тамақ жеткізіп\nақша табыңыз',
      'onb1Subtitle': 'айына 85 000 ₸ ден. Икемді кесте. Өзіңізге ыңғайлы уақытта шығыңыз.',
      'onb2Title': 'Басынан аяғына дейін\nбағыттаймыз',
      'onb2Subtitle': 'Құжаттарды жинауға және алғашқы тапсырысқа шығуға көмектесеміз.',
      'onb3Title': 'Жеке көмекші\n24/7 жаныңызда',
      'onb3Subtitle': 'Қандай құжаттар қажет? Қате шықса не істеу керек? — көмекшіден сұраңыз.',

      // Registration Cabinet
      'regCabinetTitle': 'Жеке кабинет',
      'regCabinetSubtitle': 'Көмекшімен байланысу және жұмысты бастау үшін деректерді енгізіңіз',
      'nameHint': 'Сіздің атыңыз кім?',
      'continueBtn': 'Жалғастыру',
      'privacyNotice': '«Жалғастыру» түймесін басу арқылы пайдалану шарттарын қабылдайсыз',

      // Home Hub Cards
      'greeting': 'Сәлем',
      'chooseFormat': 'Ыңғайлы жеткізу түрін таңдаңыз',
      'autoCourier': 'Автокурьер',
      'autoCourierIncome': 'күніне 3 500 ₽ бастап',
      'autoCourierDesc': 'Радиус: бүкіл қала',
      'walkCourier': 'Жаяу курьер',
      'walkCourierIncome': 'күніне 2 500 ₽ бастап',
      'walkCourierDesc': 'Радиус: өз ауданыңыз',
      'motoCourier': 'Мотокурьер',
      'motoCourierIncome': 'күніне 3 000 ₽ бастап',
      'motoCourierDesc': 'Кептеліссіз жылдам',
      'bikeCourier': 'Велокурьер',
      'bikeCourierIncome': 'күніне 2 800 ₽ бастап',
      'bikeCourierDesc': 'Жаяудан 2 есе жылдамырақ',
      'needHelpSnippet': 'Жеке көмекші',
      'needHelpSubtitle': 'Құжаттар немесе шарттар бойынша сұрақ қойыңыз >',

      // Assistant
      'assistantGreeting': 'Сәлем! 👋 Мен сіздің жеке кураторыңызбын.\n\nЖеткізу қызметіне тез тіркелуге, жұмысқа қажетті барлық жабдықтарды алуға және ертең-ақ тапсырыстарға шығуға көмектесемін.\n\nСеріктес сауалнамасын толтыру үшін төмендегі «Тіркелу» батырмасын басыңыз немесе маған сұрақ қойыңыз!',
      'chipFastReg': '🚀 Бірден тіркелу',
      'chipWalk': 'Жаяу 🚶',
      'chipBike': 'Велосипедпен 🚲',
      'chipCar': 'Автокөлікпен 🚗',
      'chipMoto': 'Мотоциклмен 🏍️',
      'chipError': '🛠️ Қолданбадағы қате / Менің салығым',
      'chipDocs': '📄 ТМД азаматтарына арналған құжаттар',
      'chipAge': '🎂 Неше жастан бастап?',
      'chipFines': '⚡ Айыппұлдар мен термосумка',
      'inputHint': 'Көмекшіге сұрақ қойыңыз...',
      'regCardTitle': 'Серіктестің ресми сауалнамасы',
            'regCardPerk1': 'Күн сайын картаға төлемдер',
            'regCardPerk2': 'Жұмысқа қажетті барлық жабдықтар',
            'regCardPerk3': '1 сағаттан басталатын еркін кесте',
            'regCardBtn': 'Анкетасын толтыру',

                  // Sticky CTA Banner
                  'cta_fill_anketa': 'Анкетасын толтыру',
                  'cta_fill_anketa_sub': 'Серіктестің ресми сауалнамасы — 2 минут',
                  'cta_continue_reg': 'Тіркеуді жалғастыру',
                  'cta_continue_reg_sub': 'Куратор қалған қадамдарды өткізуде көмектеседі',
                  'cta_get_bag': 'Сумканы алу',
                  'cta_get_bag_sub': 'Термосумканы алып, жұмыстан тысқарыға шығыңыз',
                  'cta_open_income': 'Табысты ашу',
                  'cta_open_income_sub': 'Сменадағы жұмыс ақысын есептеу',

                  // Calculator
      'calcTitle': 'Кірісті есептеу',
      'daysPerWeek': 'Аптасына күндер',
      'hoursPerDay': 'Күніне сағаттар',
      'approxIncome': 'Болжамды кіріс',
      'month': 'ай',
      'goals': 'Сіздің мақсаттарыңыз',
      'goalIphone': '📱 Жаңа iPhone 16',
      'goalScooter': '🛵 Электросамокат',
      'goalVacation': '✈️ Теңізге демалыс',
      'shifts': 'ауысым',
      'startEarning': 'Мақсатқа жету үшін бастау →',

      // Roadmap
      'roadmapTitle': '5 тапсырысқа дейінгі жолым',
      'roadmapSubtitle': 'Максималды бонустарды ашу үшін 5 жеткізуді орындаңыз!',
      'step1': 'Серіктес сауалнамасын толтыру',
      'step1Desc': 'Онлайн сауалнама 3 минут алады',
      'step2': '«Менің салығым» қолданбасына қосу',
      'step2Desc': 'Серіктестер → Еда қызметі → Рұқсат ету',
      'step3': 'Жұмысқа қажетті заттарды алу',
      'step3Desc': 'Беру пунктінде немесе курьерлік орталықта',
      'step4': 'Алғашқы орындалған тапсырыс',
      'step4Desc': 'Бірінчи ауысымда көмекшіден қолдау',
      'step5': '5 тапсырыс = Жаңа бастаушының бонусы!',
      'step5Desc': 'Максималды тарифтер мен төлемдер ашылады',
      'openGuide': '📖 Суретті нұсқаулық',
      'vpnWarning': '⚠️ Маңызды: қате туындаса, VPN өшіріңіз!',

            // Proactive Questions (Sprint 2)
            'proactive_pre_registration': 'Какой район тебе ближе для старта?',
            'proactive_registration_sent': 'Нужна инструкция по «Мой налог» прямо сейчас?',
            'proactive_post_registration': 'Какой ЦО тебе удобнее?',
            'proactive_active_courier': 'Как заказы вчера? Есть вопросы по тарифам?',
            'proactive_churned_risk': 'Что мешает выйти на линию? Могу помочь с документами/зоной.',

                        // Self-Report Buttons (Sprint 3)
                        'btnBagReceived': 'Я получил сумку',
                        'btnFirstOrderDone': 'Сделал первый заказ',
                        'btnMoyNalogLinked': 'Мой налог привязан',
                        'selfReportBagReceived': 'Отлично! Сумка получена — теперь можно выходить на заказы. Нужна помощь с первым слотом?',
                        'selfReportFirstOrderDone': '🎉 Первый заказ выполнен! Молодец. Продолжай в том же духе — к бонусам новичка близко.',
                        'selfReportMoyNalogLinked': '✅ «Мой налог» привязан. Теперь выплаты будут приходить автоматически.',
                      },

                      'uz': {
            // ... existing ...
            'vpnWarning': '⚠️ Muhim: ilovada xatolik bo\'lsa, VPN-ni o\'chiring!',

            // Proactive Questions (Sprint 2)
            'proactive_pre_registration': 'Qaysi tuman sizga yaqinroq boshlash uchun?',
            'proactive_registration_sent': 'Hozir \"Mening solig\'im\" bo\'yicha qo\'llanma kerakmi?',
            'proactive_post_registration': 'Qaysi Kuryerlik markaz sizga qulay?',
            'proactive_active_courier': 'Kecha buyurtmalar qanday edi? Tariflar bo\'yicha savollar bormi?',
            'proactive_churned_risk': 'Nima oldin isotga chiqishni to\\'xtatdi? Hujjatlar/hudud bilan yordam kerakmi?',

                        // Self-Report Buttons (Sprint 3)
                        'btnBagReceived': 'Men sumka oldim',
                        'btnFirstOrderDone': 'Birinchi buyurtmani bajardim',
                        'btnMoyNalogLinked': 'Mening solig\\'im ulangan',
                        'selfReportBagReceived': 'Ajoyib! Sumka olingan — endi buyurtmalarga chiqishingiz mumkin. Birinchi slotda yordam kerakmi?',
                        'selfReportFirstOrderDone': '🎉 Birinchi buyurtma bajarildi! Zo\'r. Shu ravishda davom eting — boshlovchi bonuslari yaqin.',
                        'selfReportMoyNalogLinked': '✅ \"Mening solig\'im\" ulangan. Endi to\'lovlar avtomatik keladi.',
                      },

                      'kg': {
            // ... existing ...
            'vpnWarning': '⚠️ Маанилүү: ката чыкса, VPN-ди өчүрүңүз!',

            // Proactive Questions (Sprint 2)
            'proactive_pre_registration': 'Кайсы район сен үчүн жакын, иштөө үчүн?',
            'proactive_registration_sent': 'Менин салыгым тууралуу көйгөй каабырда керекпи?',
            'proactive_post_registration': 'Кайсы Курьердик борбор сен үчүн ыңгайлуу?',
            'proactive_active_courier': 'Кече тапшырымдар кандай болду? Тарифтер боюнча суроолор барбы?',
            'proactive_churned_risk': 'Эмне чектеп, чогулуп калдың? Документтер/район менен жардам керекпи?',

                        // Self-Report Buttons (Sprint 3)
                        'btnBagReceived': 'Мен сумка алдым',
                        'btnFirstOrderDone': 'Биринчи тапшырма аткардым',
                        'btnMoyNalogLinked': 'Менин салыгым кошулду',
                        'selfReportBagReceived': 'Абдан жакшы! Сумка алынган — эми тапшырмаларга чыга аласыз. Биринчи сменада жардам керекпи?',
                        'selfReportFirstOrderDone': '🎉 Биринчи тапшырма аткардыл! Жакшы кетти. Ошолcha davam ettiriңиз — жаңы баштауучу бонустары жакын.',
                        'selfReportMoyNalogLinked': '✅ «Менин салыгым» кошулду. Эми төлөмдөр автоматтык келет.',
                      },

                      'kz': {
            // ... existing ...
            'vpnWarning': '⚠️ Маңызды: қате туындаса, VPN өшіріңіз!',

            // Proactive Questions (Sprint 2)
            'proactive_pre_registration': 'Бастау үшін қай аудан саған жақын?',
            'proactive_registration_sent': '«Менің салығым» бойынша нұсқаулық қазір керек пе?',
            'proactive_post_registration': 'Қай Курьерлік орталық саған ыңғайлы?',
            'proactive_active_courier': 'Кеше тапсырыстар қалай болды? Тарифтер бойынша сұрақтар бар ма?',
            'proactive_churned_risk': 'Не кедергі жасап, жолға шығуды тоқтатты? Жұжаттар/ауданмен көмек керек пе?',

                        // Self-Report Buttons (Sprint 3)
                        'btnBagReceived': 'Мен сумка аладым',
                        'btnFirstOrderDone': 'Бірінші тапсырысты орындадым',
                        'btnMoyNalogLinked': 'Менің салығым қосылды',
                        'selfReportBagReceived': 'Тамаша! Сумка алынды — енді тапсырыстарға шыға аласыз. Бірінші ауысымда көмек керек пе?',
                        'selfReportFirstOrderDone': '🎉 Бірінші тапсырыс орындалды! Жақсы кетті. Сол сияқты жалғастырыңыз — жаңа бастаушы бонустары жақын.',
                        'selfReportMoyNalogLinked': '✅ «Менің салығым» қосылды. Енді төлемдер автоматты түрде келеді.',
                      },
                    };

        static String get(String key, String lang) {
    return _strings[lang]?[key] ?? _strings['ru']?[key] ?? key;
  }
}
