class AppStrings {
  static const Map<String, Map<String, String>> _strings = {
    'ru': {
      // Common
      'appName': 'Курьер PRO Еда',
      'assistant': 'Помощник',
      'home': 'Главная',
      'income': 'Доход',
      'myPath': 'Мой путь',
      'deleteAccount': 'Удалить профиль',
      'deleteConfirm': 'Вы уверены, что хотите удалить профиль? Все сохраненные данные будут стёрты.',
      'cancel': 'Отмена',
      'delete': 'Удалить',
      'save': 'Сохранить',
      'profile': 'Личный кабинет',
      'name': 'Ваше имя',
      'phone': 'Номер телефона',
      'workCountry': 'Страна работы',
      'format': 'Формат доставки',
      'language': 'Язык приложения',
      'russia': 'Россия',
      'kazakhstan': 'Казахстан',
      'uzbekistan': 'Узбекистан',
      'kyrgyzstan': 'Кыргызстан',
      'belarus': 'Беларусь',
      'next': 'Далее →',
      'start': 'Начать →',
      
      // Language Selection
      'selectLanguage': 'Выберите язык',
      'selectLanguageSub': 'Вы сможете изменить язык в любой момент в профиле',
      
      // Onboarding
      'onb1Title': 'чаевые только\nваши',
      'onb1Subtitle': 'мы не берём с них комиссию — весь доход остаётся вам',
      'onb2Title': 'свободное\nрасписание',
      'onb2Subtitle': 'сами выбираете время. надо уйти — завершите слот',
      'onb3Title': 'выплаты\nкаждый день',
      'onb3Subtitle': 'или каждую неделю — без задержек на карту любого банка',
      'onb4Title': 'персональные\nпомощники',
      'onb4Subtitle': 'всегда на связи и ответят на любые вопросы 24/7',
      'skip': 'пропустить',
      'becomeCourier': 'стать курьером',
      'nextBtn': 'далее',

      // Registration Cabinet
      'regCabinetTitle': 'Личный кабинет',
      'regCabinetSubtitle': 'Введите данные для связи с помощником и старта работы',
      'nameHint': 'Как к вам обращаться?',
      'continueBtn': 'Продолжить',
      'privacyNotice': 'Нажимая «Продолжить», вы принимаете условия использования',
      'selectCountryCode': 'Выберите код страны',
      'invalidPhone': 'Введите корректный номер телефона',
      'defaultCourierName': 'Партнёр',

      // Home Hub Cards
      'greeting': 'Привет',
      'chooseFormatTitle': 'Формат доставки',
      'chooseFormatSub': 'Официальное подключение курьеров с ежедневными выплатами',
      'chooseFormat': 'Формат доставки',
      'autoCourier': 'Автокурьер',
      'autoCourierIncome': 'от 3 500 ₽ / день',
      'autoCourierDesc': 'Радиус: весь город',
      'autoDesc': 'На своем автомобиле или аренда со скидкой',
      'walkCourier': 'Пеший курьер',
      'walkCourierIncome': 'от 2 500 ₽ / день',
      'walkCourierDesc': 'Радиус: свой район',
      'walkBikeCourier': 'Пеший и Велокурьер',
      'walkBikeDesc': 'Свободный график от 2 часов возле дома',
      'motoCourier': 'Мотокурьер',
      'motoCourierIncome': 'от 3 000 ₽ / день',
      'motoCourierDesc': 'Без пробок и задержек',
      'motoDesc': 'Быстрая доставка на скутере или мотоцикле',
      'bikeCourier': 'Велокурьер',
      'bikeCourierIncome': 'от 2 800 ₽ / день',
      'bikeCourierDesc': 'Быстрее пешего в 2 раза',
      'tagHighIncome': 'Высокий доход',
      'tagFastStart': 'Быстрый старт',
      'tagNoTraffic': 'Без пробок',
      'assistantBadge': 'Помощник 24/7',
      'assistantTitle': 'Персональный помощник',
      'assistantDesc': 'Ответит на вопросы в чате и поможет с регистрацией 24/7',
      'writeAssistant': 'Написать помощнику',
      'needHelpSnippet': 'Персональный помощник',
      'needHelpSubtitle': 'Задайте вопрос по документам или условиям >',
      'profileTab': 'Профиль',

      // Profile & Settings
      'savedSuccessfully': 'Данные сохранены',
      'logoutTitle': 'Выйти из профиля',
      'logoutDesc': 'Вы выйдете из профиля курьера. Данные можно будет ввести заново при следующем входе.',
      'logoutBtn': 'Выйти',
      'profileData': 'Данные профиля',
      'rateApp': 'Оценить приложение',
      'rateAppDesc': 'Оставьте отзыв о работе куратора',
      'resetStage': 'Сбросить этап воронки (тест)',
      'currentStage': 'Текущий этап',
      'funnelResetSuccess': 'Воронка сброшена на Этап 1',
      'reopenOnboarding': 'Посмотреть 3D Онбординг заново',
      'candidateBadge': 'Кандидат PRO',

      // Assistant
      'assistantGreeting': 'Привет! 👋 Я твой личный куратор.\n\nПомогу быстро оформиться курьером в службу доставки, получить всё необходимое для работы и выйти на первые заказы уже завтра.\n\nНажми кнопку «Анкета» ниже, чтобы заполнить анкету партнёра за пару минут, или задай мне любой вопрос в чате!',
      'chipFastReg': '🚀 Сразу к анкете',
      'chipWalk': 'Пешком 🚶',
      'chipBike': 'На велосипеде 🚲',
      'chipCar': 'На авто 🚗',
      'chipMoto': 'На мото 🏍️',
      'chipError': '🛠️ Ошибка в приложении / Мой налог',
      'chipDocs': '📄 Документы для граждан СНГ',
      'chipAge': '🎂 Со скольки лет?',
      'chipFines': '⚡ Штрафы и термокороб',
      'inputHint': 'Задайте вопрос помощнику...',
      'regCardTitle': 'Анкета партнёра',
      'regCardPerk1': 'Выплаты каждый день на карту',
      'regCardPerk2': 'Получить необходимое для работы',
      'regCardPerk3': 'Свободный график от 1 часа',
      'regCardBtn': 'Анкета',

      // Calculator
      'calcTitle': 'Расчёт дохода',
      'daysPerWeek': 'Дней в неделю',
      'hoursPerDay': 'Часов в день',
      'approxIncome': 'Потенциальный доход',
      'month': 'мес',
      'goals': 'Ваши цели',
      'goalIphone': '📱 Новый iPhone 16',
      'goalScooter': '🛵 Электросамокат',
      'goalVacation': '✈️ Отпуск на море',
      'shifts': 'смен',
      'startEarning': 'Начать зарабатывать на цель →',

      // Roadmap
      'roadmapTitle': 'Мой путь до 5 заказов',
      'roadmapSubtitle': 'Выполните 5 доставок, чтобы закрепить статус партнёра и открыть максимальные бонусы!',
      'step1': 'Заполнить анкету партнёра',
      'step1Desc': 'Онлайн-анкета занимает 3 минуты',
      'step2': 'Связка с «Мой налог»',
      'step2Desc': 'Партнёры → Сервис Еда → Разрешить',
      'step3': 'Получить необходимое для работы',
      'step3Desc': 'В пункте выдачи (ПВЗ) или Курьерском центре',
      'step4': 'Первый выполненный заказ',
      'step4Desc': 'Поддержка на первом слоте от помощника',
      'step5': '5 заказов = Бонус новичка!',
      'step5Desc': 'Разблокировка максимальных тарифов и выплат',
      'openGuide': '📖 Пошаговая шпаргалка в картинках',
      'vpnWarning': '⚠️ Важно: при ошибках в приложении выключите VPN!',

      // Curator Funnel Chips
      'chipThanksHelper': 'Спасибо, помогло! 👍',
      'chipMoyNalog': '📲 Связка с Мой налог',
      'chipWhereIsCD': '🎒 Где забрать короб (ЦД)?',
      'chipFirstOrderGuide': '🚴‍♂️ Как проходит 1-й заказ?',
      'chipStage1Done': 'Анкета отправлена ✅',
      'chipStage2Done': 'Мой налог подключен ✅',
      'chipStage3Done': 'Забрал короб в ЦД ✅',
      'chipStage4Done': 'Вышел на 1-ю смену ✅',
      'chipStage5Done': 'Выполнил 5 заказов 🎁',

      // Courier Centers (CD)
      'cdTitle': 'Центры выдачи экипировки',
      'cdSubtitle': 'Термокороб и форма выдаются бесплатно и без залога',
      'cdFreeBadge': '0 ₽ • Без залога',
      'cdPvzNotice': 'В городах без курьерского центра экипировка выдаётся в ПВЗ Яндекс Маркета после онлайн-фотоконтроля.',
      'cdDocsRequired': 'Что взять с собой: Паспорт и телефон',

      // First shift checklist
      'checklistTitle': 'Чек-лист перед первой сменой',
      'checklistSubtitle': '5 простых пунктов для уверенного старта',
      'checkItem1': 'Зарядить телефон на 100% и взять повербанк',
      'checkItem2': 'Удобная обувь по сезону и одежда по погоде',
      'checkItem3': 'Проверить перегородку и чистоту внутри короба',
      'checkItem4': 'Установить Яндекс Про и включить геолокацию',
      'checkItem5': 'Держатель для телефона на руль (вело/мото/авто)',
    },

    'uz': {
      // Common
      'appName': 'Kuryer PRO Eda',
      'assistant': 'Yordamchi',
      'home': 'Bosh sahifa',
      'income': 'Daromad',
      'myPath': 'Mening yo‘lim',
      'deleteAccount': 'Profilni o‘chirish',
      'deleteConfirm': 'Haqiqatan ham profilingizni o‘chirmoqchimisiz? Barcha ma’lumotlar o‘chiriladi.',
      'cancel': 'Bekor qilish',
      'delete': 'O‘chirish',
      'save': 'Saqlash',
      'profile': 'Shaxsiy kabinet',
      'name': 'Ismingiz',
      'phone': 'Telefon raqam',
      'workCountry': 'Ishlash davlati',
      'format': 'Yetkazib berish turi',
      'language': 'Ilova tili',
      'russia': 'Rossiya',
      'kazakhstan': 'Qozog‘iston',
      'uzbekistan': 'O‘zbekiston',
      'kyrgyzstan': 'Qirg‘iziston',
      'belarus': 'Belarus',
      'next': 'Keyingisi →',
      'start': 'Boshlash →',
      
      // Language Selection
      'selectLanguage': 'Tilni tanlang',
      'selectLanguageSub': 'Ilova tilini profilingizda istalgan vaqtda o‘zgartirishingiz mumkin',

      // Onboarding
      'onb1Title': 'choychaqa faqat\nsizniki',
      'onb1Subtitle': 'biz ulardan komissiya olmaymiz — barcha daromad sizda qoladi',
      'onb2Title': 'erkin\njadval',
      'onb2Subtitle': 'vaqtni o‘zingiz tanlaysiz. ketish kerak bo‘lsa — slotni tugating',
      'onb3Title': 'har kuni\nto‘lovlar',
      'onb3Subtitle': 'yoki har hafta — istalgan bank kartasiga kechikishlarsiz',
      'onb4Title': 'shaxsiy\nyordamchilar',
      'onb4Subtitle': 'doim aloqada va 24/7 har qanday savollarga javob beradi',
      'skip': 'o‘tkazib yuborish',
      'becomeCourier': 'kuryer bo‘lish',
      'nextBtn': 'keyingisi',

      // Registration Cabinet
      'regCabinetTitle': 'Shaxsiy kabinet',
      'regCabinetSubtitle': 'Yordamchi bilan bog‘lanish va ish boshlash uchun ma’lumot kiriting',
      'nameHint': 'Ismingiz nima?',
      'continueBtn': 'Davom etish',
      'privacyNotice': '«Davom etish»ni bosish orqali foydalanish shartlariga rozilik bildirasiz',
      'selectCountryCode': 'Mamlakat kodini tanlang',
      'invalidPhone': 'To‘g‘ri telefon raqamini kiriting',
      'defaultCourierName': 'Hamkor',

      // Home Hub Cards
      'greeting': 'Salom',
      'chooseFormatTitle': 'Yetkazib berish turi',
      'chooseFormatSub': 'Kunlik to‘lovlar bilan kuryerlarni rasmiy ulash',
      'chooseFormat': 'Yetkazib berish turi',
      'autoCourier': 'Avto kuryer',
      'autoCourierIncome': 'kuniga 3 500 ₽ dan',
      'autoCourierDesc': 'Radius: butun shahar',
      'autoDesc': 'O‘z avtomobilingizda yoki chegirma bilan ijara',
      'walkCourier': 'Piyoda kuryer',
      'walkCourierIncome': 'kuniga 2 500 ₽ dan',
      'walkCourierDesc': 'Radius: o‘z hududingiz',
      'walkBikeCourier': 'Piyoda va Velo kuryer',
      'walkBikeDesc': 'Uy yonida 2 soatdan erkin jadval',
      'motoCourier': 'Moto kuryer',
      'motoCourierIncome': 'kuniga 3 000 ₽ dan',
      'motoCourierDesc': 'Tirbandliklarsiz tez',
      'motoDesc': 'Skuter yoki mototsiklda tez yetkazib berish',
      'bikeCourier': 'Velo kuryer',
      'bikeCourierIncome': 'kuniga 2 800 ₽ dan',
      'bikeCourierDesc': 'Piyodadan 2 barobar tez',
      'tagHighIncome': 'Yuqori daromad',
      'tagFastStart': 'Tezkor start',
      'tagNoTraffic': 'Tirbandliksiz',
      'assistantBadge': 'Yordamchi 24/7',
      'assistantTitle': 'Shaxsiy yordamchi',
      'assistantDesc': 'Chatda savollarga javob beradi va ro‘yxatdan o‘tishda 24/7 yordam beradi',
      'writeAssistant': 'Yordamchiga yozish',
      'needHelpSnippet': 'Shaxsiy yordamchi',
      'needHelpSubtitle': 'Hujjatlar yoki shartlar bo‘yicha savol bering >',
      'profileTab': 'Profil',

      // Profile & Settings
      'savedSuccessfully': 'Ma’lumotlar saqlandi',
      'logoutTitle': 'Profildan chiqish',
      'logoutDesc': 'Kuryer profilidan chiqasiz. Keyingi kirishda ma’lumotlarni qayta kiritish mumkin.',
      'logoutBtn': 'Chiqish',
      'profileData': 'Profil ma’lumotlari',
      'rateApp': 'Ilovani baholash',
      'rateAppDesc': 'Kurator ishi haqida fikr bildiring',
      'resetStage': 'Voronka bosqichini tiklash (test)',
      'currentStage': 'Joriy bosqich',
      'funnelResetSuccess': 'Voronka 1-bosqichga qaytarildi',
      'reopenOnboarding': '3D Onboardingni qayta ko‘rish',
      'candidateBadge': 'PRO nomzod',

      // Assistant
      'assistantGreeting': 'Salom! 👋 Men sizning shaxsiy kuratoringizman.\n\nYetkazib berish xizmatiga tezda ro‘yxatdan o‘tish, ish uchun zarur narsalarni olish va ertagayoq buyurtmalarga chiqishda yordam beraman.\n\nHamkor anketasini to‘ldirish uchun quyidagi «Anketa» tugmasini bosing yoki menga savol bering!',
      'chipFastReg': '🚀 To‘g‘ridan-to‘g‘ri anketaga',
      'chipWalk': 'Piyoda 🚶',
      'chipBike': 'Velosipedda 🚲',
      'chipCar': 'Avtomobilda 🚗',
      'chipMoto': 'Mototsiklda 🏍️',
      'chipError': '🛠️ Ilovada xatolik / Mening solig‘im',
      'chipDocs': '📄 MDH fuqarolari uchun hujjatlar',
      'chipAge': '🎂 Necha yoshdan?',
      'chipFines': '⚡ Jarimalar va termasumka',
      'inputHint': 'Yordamchiga savol bering...',
      'regCardTitle': 'Hamkor anketasi',
      'regCardPerk1': 'Har kuni kartaga to‘lovlar',
      'regCardPerk2': 'Ish uchun barcha zarur narsalar',
      'regCardPerk3': '1 soatdan boshlab erkin jadval',
      'regCardBtn': 'Anketa',

      // Calculator
      'calcTitle': 'Daromad hisobi',
      'daysPerWeek': 'Haftada kunlar',
      'hoursPerDay': 'Kuniga soatlar',
      'approxIncome': 'Kutilayotgan daromad',
      'month': 'oy',
      'goals': 'Sizning maqsadlaringiz',
      'goalIphone': '📱 Yangi iPhone 16',
      'goalScooter': '🛵 Elektrosamokat',
      'goalVacation': '✈️ Dengizga sayohat',
      'shifts': 'smena',
      'startEarning': 'Maqsadga erishish uchun boshlash →',

      // Roadmap
      'roadmapTitle': '5 ta buyurtmagacha yo‘lim',
      'roadmapSubtitle': 'Maksimal bonuslarni ochish uchun 5 ta buyurtmani bajaring!',
      'step1': 'Hamkor anketasini to‘ldirish',
      'step1Desc': 'Onlayn anketa 3 daqiqa oladi',
      'step2': '«Mening solig‘im»ga ulash',
      'step2Desc': 'Hamkorlar → Eda xizmati → Ruxsat berish',
      'step3': 'Ish uchun zarur narsalarni olish',
      'step3Desc': 'Berish punkti yoki kuryerlik markazida',
      'step4': 'Birinchi bajarilgan buyurtma',
      'step4Desc': 'Birinchi smenada yordamchidan ko‘mak',
      'step5': '5 ta buyurtma = Yangi boshlovchi bonusi!',
      'step5Desc': 'Maksimal tariflar va to‘lovlar ochiladi',
      'openGuide': '📖 Rasmli qo‘llanma',
      'vpnWarning': '⚠️ Muhim: ilovada xatolik bo‘lsa, VPN-ni o‘chiring!',

      // Curator Funnel Chips
      'chipThanksHelper': 'Rahmat, yordam berdi! 👍',
      'chipMoyNalog': '📲 Soliq ilovasiga ulash',
      'chipWhereIsCD': '🎒 Termosumkani qayerdan olish kerak?',
      'chipFirstOrderGuide': '🚴‍♂️ 1-buyurtma qanday bajariladi?',
      'chipStage1Done': 'Ariza yuborildi ✅',
      'chipStage2Done': 'Soliq ulandi ✅',
      'chipStage3Done': 'Termosumkani oldim ✅',
      'chipStage4Done': '1-smenaga chiqdim ✅',
      'chipStage5Done': '5 buyurtma bajarildi 🎁',

      // Courier Centers (CD)
      'cdTitle': 'Uskunalar berish markazlari',
      'cdSubtitle': 'Termosumka va kiyim-kechak bepul va garovsiz beriladi',
      'cdFreeBadge': '0 so‘m • Garovsiz',
      'cdPvzNotice': 'Kuryerlik markazi bo‘lmagan shaharlarda uskunalar onlayn fotonazoratdan so‘ng eng yaqin topshirish punktida (PVZ) beriladi.',
      'cdDocsRequired': 'O‘zingiz bilan: Pasport va telefon',

      // First shift checklist
      'checklistTitle': '1-smenadan oldingi tekshiruv ro‘yxati',
      'checklistSubtitle': 'Ishonchli boshlash uchun 5 ta oddiy qadam',
      'checkItem1': 'Telefonni 100% quvvatlab, poverbank olish',
      'checkItem2': 'Mavsumga mos qulay poyabzal va kiyim',
      'checkItem3': 'Termosumka ichidagi to‘siq va tozalikni tekshirish',
      'checkItem4': 'Yandex Pro ilovasini o‘rnatib, geolokatsiyani yoqish',
      'checkItem5': 'Rulga telefon ushlagich (velo/moto/avto)',
    },

    'kg': {
      // Common
      'appName': 'Курьер PRO Еда',
      'assistant': 'Жардамчы',
      'home': 'Башкы бет',
      'income': 'Киреше',
      'myPath': 'Менин жолум',
      'deleteAccount': 'Профилди өчүрүү',
      'deleteConfirm': 'Чын эле профилди өчүргүңүз келеби? Бардык маалыматтар өчүрүлөт.',
      'cancel': 'Жокко чыгаруу',
      'delete': 'Өчүрүү',
      'save': 'Сактоо',
      'profile': 'Жеке кабинет',
      'name': 'Сиздин атыңыз',
      'phone': 'Телефон номери',
      'workCountry': 'Иштөө өлкөсү',
      'format': 'Жеткирүү түрү',
      'language': 'Тилди тандоо',
      'russia': 'Россия',
      'kazakhstan': 'Казакстан',
      'uzbekistan': 'Өзбекстан',
      'kyrgyzstan': 'Кыргызстан',
      'belarus': 'Беларусь',
      'next': 'Андан ары →',
      'start': 'Баштоо →',

      // Language Selection
      'selectLanguage': 'Тилди тандаңыз',
      'selectLanguageSub': 'Тилди профилден каалаган убакта өзгөртө аласыз',

      // Onboarding
      'onb1Title': 'чай пулдары\nсиздики',
      'onb1Subtitle': 'биз алардан комиссия албайбыз — бардык киреше сизде калат',
      'onb2Title': 'эркин\nграфик',
      'onb2Subtitle': 'убакытты өзүңүз тандайсыз. кетүү керек болсо — слотту бүтүрүңүз',
      'onb3Title': 'күн сайын\nтөлөмдөр',
      'onb3Subtitle': 'же жума сайын — каалаган банктын картасына кечиктирбей',
      'onb4Title': 'жеке\nжардамчылар',
      'onb4Subtitle': 'дайыма байланышта жана 24/7 бардык суроолорго жооп берет',
      'skip': 'өткөрүп жиберүү',
      'becomeCourier': 'курьер болуу',
      'nextBtn': 'кийинки',

      // Registration Cabinet
      'regCabinetTitle': 'Жеке кабинет',
      'regCabinetSubtitle': 'Жардамчы менен байланышуу жана ишти баштоо үчүн маалымат жазыңыз',
      'nameHint': 'Атыңыз ким?',
      'continueBtn': 'Улантуу',
      'privacyNotice': '«Улантуу» баскычын басуу менен колдонуу шарттарына макул болосуз',
      'selectCountryCode': 'Өлкө кодун тандаңыз',
      'invalidPhone': 'Туура телефон номерин киргизиңиз',
      'defaultCourierName': 'Шериктеш',

      // Home Hub Cards
      'greeting': 'Салам',
      'chooseFormatTitle': 'Жеткирүү форматы',
      'chooseFormatSub': 'Күн сайын төлөмдөр менен курьерлерди расмий кошуу',
      'chooseFormat': 'Жеткирүү форматы',
      'autoCourier': 'Автокурьер',
      'autoCourierIncome': 'күнүнө 3 500 ₽ дан',
      'autoCourierDesc': 'Радиус: бүтүндөй шаар',
      'autoDesc': 'Өз автоңузда же жеңилдик менен ижара',
      'walkCourier': 'Жөө курьер',
      'walkCourierIncome': 'күнүнө 2 500 ₽ дан',
      'walkCourierDesc': 'Радиус: өз районуңуз',
      'walkBikeCourier': 'Жөө жана Велокурьер',
      'walkBikeDesc': 'Үй жанында 2 сааттан эркин график',
      'motoCourier': 'Мотокурьер',
      'motoCourierIncome': 'күнүнө 3 000 ₽ дан',
      'motoCourierDesc': 'Тыгындарсыз тез',
      'motoDesc': 'Скутер же мотоциклде тез жеткирүү',
      'bikeCourier': 'Велокурьер',
      'bikeCourierIncome': 'күнүнө 2 800 ₽ дан',
      'bikeCourierDesc': 'Жөө баскандан 2 эсе ылдам',
      'tagHighIncome': 'Жогорку киреше',
      'tagFastStart': 'Тез баштоо',
      'tagNoTraffic': 'Тыгынсыз',
      'assistantBadge': 'Жардамчы 24/7',
      'assistantTitle': 'Жеке жардамчы',
      'assistantDesc': 'Чатта суроолорго жооп берип, 24/7 катталууга жардам берет',
      'writeAssistant': 'Жардамчыга жазуу',
      'needHelpSnippet': 'Жеке жардамчы',
      'needHelpSubtitle': 'Документтер же шарттар боюнча суроо бериңиз >',
      'profileTab': 'Профиль',

      // Profile & Settings
      'savedSuccessfully': 'Маалыматтар сакталды',
      'logoutTitle': 'Профилден чыгуу',
      'logoutDesc': 'Курьер профилинен чыгасыз. Маалыматтарды кайра киргизүүгө болот.',
      'logoutBtn': 'Чыгуу',
      'profileData': 'Профиль маалыматтары',
      'rateApp': 'Колдонмону баалоо',
      'rateAppDesc': 'Куратордун ишине баа бериңиз',
      'resetStage': 'Воронка этабын баштапкы абалга келтирүү (тест)',
      'currentStage': 'Учурдагы этап',
      'funnelResetSuccess': 'Воронка 1-этапка кайтарылды',
      'reopenOnboarding': '3D Онбордингди кайра көрүү',
      'candidateBadge': 'PRO талапкер',

      // Assistant
      'assistantGreeting': 'Салам! 👋 Мен сиздин жеке кураторуңузмун.\n\nЖеткирүү кызматына тез катталууга, иш үчүн керектүү бардык нерселерди алууга жана эртең эле буйрутмаларга чыгууга жардам берем.\n\nӨнөктөш анкетасын толтуруу үчүн төмөнкү «Анкета» баскычын басыңыз же мага суроо бериңиз!',
      'chipFastReg': '🚀 Дароо анкетага',
      'chipWalk': 'Жөө 🚶',
      'chipBike': 'Велосипед менен 🚲',
      'chipCar': 'Авто менен 🚗',
      'chipMoto': 'Мото менен 🏍️',
      'chipError': '🛠️ Тиркемедеги ката / Менин салыгым',
      'chipDocs': '📄 КМШ жарандары үчүн документтер',
      'chipAge': '🎂 Канча жаштан?',
      'chipFines': '⚡ Айыптар жана термосумка',
      'inputHint': 'Жардамчыга суроо бериңиз...',
      'regCardTitle': 'Өнөктөштүн расмий анкетасы',
      'regCardPerk1': 'Күндө картага төлөмдөр',
      'regCardPerk2': 'Иш үчүн керектүү бардык нерселер',
      'regCardPerk3': '1 сааттан баштап бош график',
      'regCardBtn': 'Анкета',

      // Calculator
      'calcTitle': 'Киреше эсептөө',
      'daysPerWeek': 'Аптадагы күндөр',
      'hoursPerDay': 'Күндөгү сааттар',
      'approxIncome': 'Болжолдуу киреше',
      'month': 'ай',
      'goals': 'Сиздин максаттар',
      'goalIphone': '📱 Жаңы iPhone 16',
      'goalScooter': '🛵 Электросамокат',
      'goalVacation': '✈️ Деңизге эс алуу',
      'shifts': 'смена',
      'startEarning': 'Максатка жетүү үчүн баштоо →',

      // Roadmap
      'roadmapTitle': '5 тапшырыкка чейин жолум',
      'roadmapSubtitle': 'Максималдуу бонустарды алуу үчүн 5 жеткирүүнү аткарыңыз!',
      'step1': 'Өнөктөш анкетасын толтуруу',
      'step1Desc': 'Онлайн анкета 3 мүнөт алат',
      'step2': '«Менин салыгым» тиркемесине кошуу',
      'step2Desc': 'Өнөктөштөр → Еда кызматы → Уруксат берүү',
      'step3': 'Иш үчүн керектүү нерселерди алуу',
      'step3Desc': 'Берүү түйүнүндө же курьердик борбордо',
      'step4': 'Биринчи аткарылган тапшырык',
      'step4Desc': 'Биринчи сменде жардамчыдан колдоо',
      'step5': '5 тапшырык = Жаңы баштагандын бонусу!',
      'step5Desc': 'Максималдуу тарифтер жана төлөмдөр ачылат',
      'openGuide': '📖 Сүрөттүү колдонмо',
      'vpnWarning': '⚠️ Маанилүү: ката чыкса, VPN-ди өчүрүңүз!',

      // Curator Funnel Chips
      'chipThanksHelper': 'Рахмат, жардам берди! 👍',
      'chipMoyNalog': '📲 Салыкка кошуу',
      'chipWhereIsCD': '🎒 Сумканы кайдан алса болот?',
      'chipFirstOrderGuide': '🚴‍♂️ 1-буйрутма кандай аткарылат?',
      'chipStage1Done': 'Анкета жөнөтүлдү ✅',
      'chipStage2Done': 'Салык кошулду ✅',
      'chipStage3Done': 'Сумканы алдым ✅',
      'chipStage4Done': '1-сменага чыктым ✅',
      'chipStage5Done': '5 буйрутма аткарылды 🎁',

      // Courier Centers (CD)
      'cdTitle': 'Экипировка берүү борборлору',
      'cdSubtitle': 'Термосумка жана форма бекер жана күрөөсүз берилет',
      'cdFreeBadge': '0 сом • Күрөөсүз',
      'cdPvzNotice': 'Курьердик борбору жок шаарларда экипировка онлайн фотокөзөмөлдөн кийин ПВЗда берилет.',
      'cdDocsRequired': 'Өзүңүз менен: Паспорт жана телефон',

      // First shift checklist
      'checklistTitle': '1-смена алдындагы текшерүү тизмеси',
      'checklistSubtitle': 'Ишенимдүү баштоо үчүн 5 жөнөкөй кадам',
      'checkItem1': 'Телефонду 100% кубаттап, пауэрбанк алуу',
      'checkItem2': 'Мезгилге ылайыктуу бут кийим жана кийим',
      'checkItem3': 'Сумканын ичиндеги тосмону жана тазалыкты текшерүү',
      'checkItem4': 'Яндекс Про орнотуп, геолокацияны күйгүзүү',
      'checkItem5': 'Рульга телефон кармагыч (вело/мото/авто)',
    },

    'kz': {
      // Common
      'appName': 'Курьер PRO Еда',
      'assistant': 'Көмекші',
      'home': 'Басты бет',
      'income': 'Кіріс',
      'myPath': 'Менің жолым',
      'deleteAccount': 'Профильді жою',
      'deleteConfirm': 'Профильді жойғыңыз келетініне сенімдісіз бе? Барлық сақталған деректер өшіріледі.',
      'cancel': 'Бас тарту',
      'delete': 'Жою',
      'save': 'Сақтау',
      'profile': 'Жеке кабинет',
      'name': 'Сіздің атыңыз',
      'phone': 'Телефон нөмірі',
      'workCountry': 'Жұмыс елі',
      'format': 'Жеткізу түрі',
      'language': 'Қолданба тілі',
      'russia': 'Ресей',
      'kazakhstan': 'Қазақстан',
      'uzbekistan': 'Өзбекстан',
      'kyrgyzstan': 'Қырғызстан',
      'belarus': 'Беларусь',
      'next': 'Келесі →',
      'start': 'Бастау →',

      // Language Selection
      'selectLanguage': 'Тілді таңдаңыз',
      'selectLanguageSub': 'Тілді кез келген уақытта профильден өзгерте аласыз',

      // Onboarding
      'onb1Title': 'шайпұл тек\nсіздікі',
      'onb1Subtitle': 'біз олардан комиссия алмаймыз — барлық кіріс өзіңізде қалады',
      'onb2Title': 'еркін\nкесте',
      'onb2Subtitle': 'уақытты өзіңіз таңдайсыз. кету керек болса — слотты аяқтаңыз',
      'onb3Title': 'күн сайын\nтөлемдер',
      'onb3Subtitle': 'немесе әр апта сайын — кез келген банк картасына кідіріссіз',
      'onb4Title': 'жеке\nкөмекшілер',
      'onb4Subtitle': 'әрдайым байланыста және 24/7 кез келген сұраққа жауап береді',
      'skip': 'өткізіп жіберу',
      'becomeCourier': 'курьер болу',
      'nextBtn': 'келесі',

      // Registration Cabinet
      'regCabinetTitle': 'Жеке кабинет',
      'regCabinetSubtitle': 'Көмекшімен байланысу және жұмысты бастау үшін деректерді енгізіңіз',
      'nameHint': 'Сіздің атыңыз кім?',
      'continueBtn': 'Жалғастыру',
      'privacyNotice': '«Жалғастыру» түймесін басу арқылы пайдалану шарттарын қабылдайсыз',
      'selectCountryCode': 'Ел кодын таңдаңыз',
      'invalidPhone': 'Дұрыс телефон нөмірін енгізіңіз',
      'defaultCourierName': 'Серіктес',

      // Home Hub Cards
      'greeting': 'Сәлем',
      'chooseFormatTitle': 'Жеткізу түрі',
      'chooseFormatSub': 'Күнделікті төлемдермен курьерлерді ресми қосу',
      'chooseFormat': 'Жеткізу түрі',
      'autoCourier': 'Автокурьер',
      'autoCourierIncome': 'күніне 3 500 ₽ бастап',
      'autoCourierDesc': 'Радиус: бүкіл қала',
      'autoDesc': 'Өз автокөлігіңізде немесе жеңілдікпен жалдау',
      'walkCourier': 'Жаяу курьер',
      'walkCourierIncome': 'күніне 2 500 ₽ бастап',
      'walkCourierDesc': 'Радиус: өз ауданыңыз',
      'walkBikeCourier': 'Жаяу және Велокурьер',
      'walkBikeDesc': 'Үй жанында 2 сағаттан еркін кесте',
      'motoCourier': 'Мотокурьер',
      'motoCourierIncome': 'күніне 3 000 ₽ бастап',
      'motoCourierDesc': 'Кептеліссіз жылдам',
      'motoDesc': 'Скутер немесе мотоциклде жылдам жеткізу',
      'bikeCourier': 'Велокурьер',
      'bikeCourierIncome': 'күніне 2 800 ₽ бастап',
      'bikeCourierDesc': 'Жаяудан 2 есе жылдамырақ',
      'tagHighIncome': 'Жоғары кіріс',
      'tagFastStart': 'Жылдам бастау',
      'tagNoTraffic': 'Кептеліссіз',
      'assistantBadge': 'Көмекші 24/7',
      'assistantTitle': 'Жеке көмекші',
      'assistantDesc': 'Чатта сұрақтарға жауап беріп, 24/7 тіркелуге көмектеседі',
      'writeAssistant': 'Көмекшіге жазу',
      'needHelpSnippet': 'Жеке көмекші',
      'needHelpSubtitle': 'Құжаттар немесе шарттар бойынша сұрақ қойыңыз >',
      'profileTab': 'Профиль',

      // Profile & Settings
      'savedSuccessfully': 'Деректер сақталды',
      'logoutTitle': 'Профильден шығу',
      'logoutDesc': 'Курьер профилінен шығасыз. Келесі жолы кіргенде деректерді қайта енгізуге болады.',
      'logoutBtn': 'Шығу',
      'profileData': 'Профиль деректері',
      'rateApp': 'Қолданбаны бағалау',
      'rateAppDesc': 'Куратордың жұмысы туралы пікір қалдырыңыз',
      'resetStage': 'Воронка кезеңін қалпына келтіру (тест)',
      'currentStage': 'Ағымдағы кезең',
      'funnelResetSuccess': 'Воронка 1-кезеңге қайтарылды',
      'reopenOnboarding': '3D Онбордингті қайта көру',
      'candidateBadge': 'PRO үміткер',

      // Assistant
      'assistantGreeting': 'Сәлем! 👋 Мен сіздің жеке кураторыңызбын.\n\nЖеткізу қызметіне тез тіркелуге, жұмысқа қажетті барлық жабдықтарды алуға және ертең-ақ тапсырыстарға шығуға көмектесемін.\n\nСеріктес сауалнамасын толтыру үшін төмендегі «Анкета» батырмасын басыңыз немесе маған сұрақ қойыңыз!',
      'chipFastReg': '🚀 Бірден сауалнамаға',
      'chipWalk': 'Жаяу 🚶',
      'chipBike': 'Велосипедпен 🚲',
      'chipCar': 'Автокөлікпен 🚗',
      'chipMoto': 'Мотоциклмен 🏍️',
      'chipError': '🛠️ Қолданбадағы қате / Менің салығым',
      'chipDocs': '📄 ТМД азаматтарына арналған құжаттар',
      'chipAge': '🎂 Неше жастан бастап?',
      'chipFines': '⚡ Айыппұлдар мен термосумка',
      'inputHint': 'Көмекшіге сұрақ қойыңыз...',
      'regCardTitle': 'Серіктестің ресми сауалнамасы',
      'regCardPerk1': 'Күн сайын картаға төлемдер',
      'regCardPerk2': 'Жұмысқа қажетті барлық жабдықтар',
      'regCardPerk3': '1 сағаттан басталатын еркін кесте',
      'regCardBtn': 'Анкета',

      // Calculator
      'calcTitle': 'Кірісті есептеу',
      'daysPerWeek': 'Аптасына күндер',
      'hoursPerDay': 'Күніне сағаттар',
      'approxIncome': 'Болжамды кіріс',
      'month': 'ай',
      'goals': 'Сіздің мақсаттарыңыз',
      'goalIphone': '📱 Жаңа iPhone 16',
      'goalScooter': '🛵 Электросамокат',
      'goalVacation': '✈️ Теңізге демалыс',
      'shifts': 'ауысым',
      'startEarning': 'Мақсатқа жету үшін бастау →',

      // Roadmap
      'roadmapTitle': '5 тапсырысқа дейінгі жолым',
      'roadmapSubtitle': 'Максималды бонустарды ашу үшін 5 жеткізуді орындаңыз!',
      'step1': 'Серіктес сауалнамасын толтыру',
      'step1Desc': 'Онлайн сауалнама 3 минут алады',
      'step2': '«Менің салығым» қолданбасына қосу',
      'step2Desc': 'Серіктестер → Еда қызметі → Рұқсат ету',
      'step3': 'Жұмысқа қажетті заттарды алу',
      'step3Desc': 'Беру пунктінде немесе курьерлік орталықта',
      'step4': 'Алғашқы орындалған тапсырыс',
      'step4Desc': 'Бірінчи ауысымда көмекшіден қолдау',
      'step5': '5 тапсырыс = Жаңа бастаушының бонусы!',
      'step5Desc': 'Максималды тарифтер мен төлемдер ашылады',
      'openGuide': '📖 Суретті нұсқаулық',
      'vpnWarning': '⚠️ Маңызды: қате туындаса, VPN өшіріңіз!',

      // Curator Funnel Chips
      'chipThanksHelper': 'Рақмет, көмектесті! 👍',
      'chipMoyNalog': '📲 Салыққа қосу',
      'chipWhereIsCD': '🎒 Термосумканы қайдан алу керек?',
      'chipFirstOrderGuide': '🚴‍♂️ 1-тапсырыс қалай орындалады?',
      'chipStage1Done': 'Сауалнама жіберілді ✅',
      'chipStage2Done': 'Салық қосылды ✅',
      'chipStage3Done': 'Термосумканы алдым ✅',
      'chipStage4Done': '1-ауысымға шықтым ✅',
      'chipStage5Done': '5 тапсырыс орындалды 🎁',

      // Courier Centers (CD)
      'cdTitle': 'Жабдықтарды беру орталықтары',
      'cdSubtitle': 'Термосумка мен форма тегін және кепілсіз беріледі',
      'cdFreeBadge': '0 ₸ • Кепілсіз',
      'cdPvzNotice': 'Курьерлік орталығы жоқ қалаларда жабдықтар онлайн фотобақылаудан кейін ПВЗ-да беріледі.',
      'cdDocsRequired': 'Өзіңізбен бірге: Төлқұжат және телефон',

      // First shift checklist
      'checklistTitle': '1-ауысым алдындағы тексеру парағы',
      'checklistSubtitle': 'Сенімді бастау үшін 5 қарапайым қадам',
      'checkItem1': 'Телефонды 100% қуаттап, повербанк алу',
      'checkItem2': 'Маусымға сәйкес ыңғайлы аяқ киім мен киім',
      'checkItem3': 'Термосумканың ішіндегі қалқаны және тазалықты тексеру',
      'checkItem4': 'Яндекс Про орнатып, геолокацияны қосу',
      'checkItem5': 'Рөлге телефон ұстағыш (вело/мото/авто)',
    },
  };

  static String get(String key, String lang) {
    return _strings[lang]?[key] ?? _strings['ru']?[key] ?? key;
  }
}
