workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
    scripts:
      - name: Set up code signing settings
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "com.fastjob.courier.pro.eat" --project-type ios --create --distribution-type app_store
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build Flutter iOS IPA
        script: |
          flutter build ipa --release --export-options-plist=$HOME/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - mtrg4tptyd@privaterelay.appleid.com
