name: fast_courier_app
description: "A new Flutter project."
publish_to: 'none'
version: 4.0.0+26

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: any
  in_app_review: any
  firebase_core: any
  firebase_messaging: any
  firebase_analytics: any
  shared_preferences: any
  provider: any
  flutter_rustore_review: 10.0.0
  cloud_firestore: any
  webview_flutter: any
  url_launcher: any
  http: any
  intl: any
  flutter_local_notifications: any
  timezone: any
  country_flags: ^3.2.0
  google_fonts: ^6.3.2
  phosphoricons_flutter: any
  device_info_plus: ^10.1.0
  # yandex_appmetrica: ^5.0.0  # TODO: find correct package name on pub.dev

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  flutter_launcher_icons: any

flutter:
  uses-material-design: true

  assets:
      - assets/app_icon.png
      - assets/app_icon_pro_eda.png
      - assets/main_banner.png
      - assets/onboarding/
      - assets/onboarding/onb_coins_100pct.png
      - assets/onboarding/onb_timer_walk.png
      - assets/onboarding/onb_wallet_coins.webp
      - assets/onboarding/onb_support_24_7.png
      - assets/onboarding/onb_phone_route.png
      - assets/onboarding/onb_courier_uniform.png
      - assets/onboarding/onb_coin_cursor.png
      - assets/country_config/
      - assets/config/ab_config.json

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter_regular.ttf
          weight: 400
        - asset: assets/fonts/inter_medium.ttf
          weight: 500
        - asset: assets/fonts/inter_semibold.ttf
          weight: 600
        - asset: assets/fonts/inter_bold.ttf
          weight: 700
        - asset: assets/fonts/inter_black.ttf
          weight: 900
    - family: MontFamily
      fonts:
        - asset: assets/fonts/inter_regular.ttf
          weight: 400
        - asset: assets/fonts/inter_medium.ttf
          weight: 500
        - asset: assets/fonts/inter_semibold.ttf
          weight: 600
        - asset: assets/fonts/inter_bold.ttf
          weight: 700
        - asset: assets/fonts/inter_black.ttf
          weight: 900
    - family: GolosText
      fonts:
        - asset: assets/fonts/golos/GolosText-VariableFont_wght.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon_pro_eda.png"
  adaptive_icon_background: "#FCE000"
  adaptive_icon_foreground: "assets/app_icon_pro_eda.png"