name: fast_courier_app
description: "A new Flutter project."
publish_to: 'none'
version: 3.5.0+13

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: any
  in_app_review: any
  firebase_core: ^4.12.0
  firebase_messaging: ^16.4.0
  firebase_analytics: ^12.4.0
  shared_preferences: any
  provider: any
  flutter_rustore_review: any
  cloud_firestore: ^6.7.0
  webview_flutter: any
  url_launcher: any
  intl: any
  flutter_local_notifications: any
  timezone: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  flutter_launcher_icons: any

flutter:
  uses-material-design: true

  assets:
    - assets/app_icon.png
    - assets/main_banner.png

  fonts:
    - family: MontFamily
      fonts:
        - asset: assets/fonts/inter_semibold.ttf
          weight: 600
        - asset: assets/fonts/inter_bold.ttf
          weight: 700
        - asset: assets/fonts/inter_black.ttf
          weight: 900

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#FFC107"
  adaptive_icon_foreground: "assets/app_icon.png"
