// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXwODJZEWsUpPnBC4E9x-GpuWadhBTUSg',
    appId: '1:798894228627:android:cefdf2e3876fa6053b3966',
    messagingSenderId: '798894228627',
    projectId: 'courier-f5652',
    storageBucket: 'courier-f5652.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6OGogSSy3o_scZLQ908Bkbu_zu0-G3Zw',
    appId: '1:798894228627:ios:4120c890b54b1d403b3966',
    messagingSenderId: '798894228627',
    projectId: 'courier-f5652',
    storageBucket: 'courier-f5652.firebasestorage.app',
    iosBundleId: 'com.fastjob.courier.pro.eat',
  );
}
